"""empty message

Revision ID: 0fe73feec23d
Revises: b45a8cd923ef
Create Date: 2021-04-16 20:49:31.652797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0fe73feec23d'
down_revision = 'b45a8cd923ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planets', 'population',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planets', 'population',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
